input: https://gist.githubusercontent.com/BrunoGrandePhD/6869bf506e6acf7b920a22b666f4e443/raw/ff7ea0757ebbd324cd125b1d48f54e6ec9f969c9/sarek-test.tsv
skip_qc: "bamqc,baserecalibrator,bcftools,documentation,markduplicates,multiqc,samtools,sentieon,vcftools,versions"
no_intervals: true
skip_markduplicates: true
known_indels: null
fasta: /home/ssm-user/sarek/work/stage/e9/74e44ffc300ee9371b47eb62399ce7/human_g1k_v37_decoy.small.fasta
fasta_fai: /home/ssm-user/sarek/work/12/ebe56df669dc436ff0c96b64e35a06/human_g1k_v37_decoy.small.fasta.fai
bwa: /home/ssm-user/sarek/work/34/23a61e196f46d9c9b20a69184beae2/human_g1k_v37_decoy.small.fasta.{amb,ann,bwt,pac,sa}
